### ISSUE TITLE
IDEA2020.1.1 安装不了

### ISSUE THREAD

**Issue by C10udx** [yisier/thief-book-idea#18]
![image](https://user-images.githubusercontent.com/44664987/85532442-49c58680-b642-11ea-97ab-f1c819021d48.png)
版本不对，还能支持么？

**Comment by yisier** [comment]
已经上传的新版本支持2020

**Comment by C10udx** [comment]
谢谢老哥，我自己也参照https://github.com/mine-riko/thief-java编译了一版，有点小bug，O(∩_∩)O哈哈~
