### ISSUE TITLE
安装好插件后，选择书籍，打开任然乱码，不能正常显示，而是一个个的小框

### ISSUE THREAD

**Issue by sam799** [yisier/thief-book-idea#20]
安装好插件后，选择书籍，修改为utf-8任然乱码，不能正常显示，而是一个个的小方框，但是将文字复制，粘贴到txt是正常的编码
![bug](https://user-images.githubusercontent.com/50124770/94389338-39153700-0182-11eb-92e3-4f6637165ec0.jpg)

**Comment by yisier** [comment]
选择系统中有的字体，比如微软雅黑
