### ISSUE TITLE
2020.2根本看不了，全是方块，自己建的txt写点中文都不显示

### ISSUE THREAD

**Issue by wjc1243** [yisier/thief-book-idea#23]
什么编码都不行

**Comment by HallenW** [comment]
用这个吧 好用多了  https://github.com/41369ly/touch-fish

**Comment by HallenW** [comment]
> 什么编码都不行

用这个吧 好用多了 https://github.com/41369ly/touch-fish

**Comment by C10udx** [comment]
> 什么编码都不行

ANSI的试过没？

**Comment by xiaguangbing** [comment]
字体换成“宋体”，“楷体”之类的中文字体

**Comment by yisier** [comment]
> 什么编码都不行

字体选择微软雅黑
