### ISSUE TITLE
设置每行页数的值后仍会出现实际与设置不匹配的情况

### ISSUE THREAD

**Issue by zqian11** [yisier/thief-book-idea#24]
![image](https://user-images.githubusercontent.com/29586955/99149026-739d4980-26c6-11eb-9105-83795bd339f9.png)
![image](https://user-images.githubusercontent.com/29586955/99149029-7b5cee00-26c6-11eb-83bb-2e9845fbdf91.png)
![image](https://user-images.githubusercontent.com/29586955/99149039-857eec80-26c6-11eb-9d24-b86d098cdf50.png)
如图设置的2，显示的时候仍会出现3行的情况

**Comment by yisier** [comment]
> ![image](https://user-images.githubusercontent.com/29586955/99149026-739d4980-26c6-11eb-9105-83795bd339f9.png)
> ![image](https://user-images.githubusercontent.com/29586955/99149029-7b5cee00-26c6-11eb-83bb-2e9845fbdf91.png)
> ![image](https://user-images.githubusercontent.com/29586955/99149039-857eec80-26c6-11eb-9d24-b86d098cdf50.png)
> 如图设置的2，显示的时候仍会出现3行的情况

这里的两行不是在控制面板显示两行，而是每次读取两行txt文件内容
