### ISSUE TITLE
关掉console后，我应该怎么重新打开？

### ISSUE THREAD

**Issue by C10udx** [yisier/thief-book-idea#3]
![image](https://user-images.githubusercontent.com/44664987/62019121-01160b00-b1f0-11e9-8fc0-636e706fbb55.png)

**Comment by yisier** [comment]
这里空白是因为没有读到文件，在thief-config选择完文件后需要重启IDEA

**Comment by C10udx** [comment]
> 这里空白是因为没有读到文件，在thief-config选择完文件后需要重启IDEA

我选择了文件，并且可以看，然后关掉了console
![image](https://user-images.githubusercontent.com/44664987/62042150-faa78380-b22f-11e9-9f90-b9b21fa9c9aa.png)
请问怎么再次打开console？

**Comment by yisier** [comment]
新版本在window 菜单下新增了一个show thief ，可以重新下载一下

**Comment by C10udx** [comment]
> 新版本在window 菜单下新增了一个show thief ，可以重新下载一下

![image](https://user-images.githubusercontent.com/44664987/62092540-19496100-b2a8-11e9-9b21-f6694f1262c6.png)
卸载了重新安装的最新版，尝试关掉这个console。
![image](https://user-images.githubusercontent.com/44664987/62092639-77764400-b2a8-11e9-8c26-3903e2e67744.png)
再在window下点击show thief，console没有出现。
重启idea，console就又出来了。
