### ISSUE TITLE
自定义快捷键的问题

### ISSUE THREAD

**Issue by OliverMilk** [yisier/thief-book-idea#30]
没有POM？代码拉下来找不到包  如果手动引入的包能不能把jar包放到代码里？这样我可以自己修改快捷键然后自己打包用

**Comment by yisier** [comment]
> 没有POM？代码拉下来找不到包 如果手动引入的包能不能把jar包放到代码里？这样我可以自己修改快捷键然后自己打包用

1.没有POM
2.不需要任何依赖jar包
3.如果不知道怎么开发jetbrains插件，请查看官网教程：https://plugins.jetbrains.com/docs/intellij/getting-started.html
