### ISSUE TITLE
不显示小说内容  快捷键无效

### ISSUE THREAD

**Issue by black72** [yisier/thief-book-idea#32]
![图片](https://user-images.githubusercontent.com/42559553/118594689-6af41000-b7dc-11eb-8d70-1004da126ba4.png)

**Comment by markcwg** [comment]
我也遇到了这个问题，Memory leak detection has started....，大佬找到解决办法了吗

**Comment by yisier** [comment]
这是一个标语，点击一下刷新按钮就好了

**Comment by Mrli2016** [comment]
> 这是一个标语，点击一下刷新按钮就好了

点了刷新也没用，还是显示这个提示
