### ISSUE TITLE
不会用。。。

### ISSUE THREAD

**Issue by spooli** [yisier/thief-book-idea#4]
难受

**Comment by yisier** [comment]
第一步：到release中下载jar包;
第二步：打开IDEA,找到setting 中的plugin，点击Install Plugin from disk选择下载的jar包，安装并重启IDEA;
第三步：进入IDEA的Setting页面，找到Tools\Thief-Book Config选项，选择txt文件，设置好自动翻页秒数后，重启IDEA;
第四步：愉快的摸鱼吧！！！！

**Comment by linmeon** [comment]
"进入IDEA的Setting页面，找到Tools\Thief-Book Config选项"没有这个选项，可以发一下截图么？
