### ISSUE TITLE
提个小建议，不知道可不可以实现

### ISSUE THREAD

**Issue by C10udx** [yisier/thief-book-idea#5]
![image](https://user-images.githubusercontent.com/44664987/62175700-2da56080-b371-11e9-8e9c-0acd25475921.png)
可以在通知栏显示吗？这样的话应该更隐蔽。

**Comment by C10udx** [comment]
> ![image](https://user-images.githubusercontent.com/44664987/62175700-2da56080-b371-11e9-8e9c-0acd25475921.png)
> 可以在通知栏显示吗？这样的话应该更隐蔽。

![image](https://user-images.githubusercontent.com/44664987/62175915-f5eae880-b371-11e9-9c18-990665b6f1b0.png)

**Comment by yisier** [comment]
> > ![image](https://user-images.githubusercontent.com/44664987/62175700-2da56080-b371-11e9-8e9c-0acd25475921.png)
> > 可以在通知栏显示吗？这样的话应该更隐蔽。
> 
> ![image](https://user-images.githubusercontent.com/44664987/62175915-f5eae880-b371-11e9-9c18-990665b6f1b0.png)

我研究一下
