### ISSUE TITLE
布局会出现问题

### ISSUE THREAD

**Issue by yisany** [yisier/thief-book-idea#8]
有时候布局是正常的:
![rightImage](https://user-images.githubusercontent.com/45846406/62931108-4fcac400-bdf0-11e9-899e-622bef79c8d6.jpg)
但有时候布局又是错误的：
![errorImage](https://user-images.githubusercontent.com/45846406/62931128-5c4f1c80-bdf0-11e9-99f8-fca02f4da0f6.jpg)

**Comment by yisier** [comment]
> 有时候布局是正常的:
> ![rightImage](https://user-images.githubusercontent.com/45846406/62931108-4fcac400-bdf0-11e9-899e-622bef79c8d6.jpg)
> 但有时候布局又是错误的：
> ![errorImage](https://user-images.githubusercontent.com/45846406/62931128-5c4f1c80-bdf0-11e9-99f8-fca02f4da0f6.jpg)

最近太忙了，等我有时间优化下UI吧
